# Generated by Django 5.0.3 on 2024-04-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("starting_bid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.URLField(help_text="Insert URL for prodcut image here"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electronics", "Electronics"),
                            ("fashion", "Fashion"),
                            ("sports_hobbies", "Sports and Hobbies"),
                            ("house_garden", "House and Garden"),
                            ("books_movies_music", "Books, Movies, Music"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=64,
                    ),
                ),
            ],
        ),
    ]
