# Generated by Django 5.0.3 on 2024-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(default="Others", max_length=64),
        ),
    ]
